[package]
name = "shelp"
description="A interactive shell, helper library"
version = "0.1.0"
authors = ["Lutetium-Vanadium"]
edition = "2018"
license="MIT"
homepage="https://github.com/Lutetium-Vanadium/shelp"
repository="https://github.com/Lutetium-Vanadium/shelp"
readme="README.md"
documentation="https://github.com/Lutetium-Vanadium/shelp"

[dependencies]
crossterm = "0.18.2"
